version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: highlight.js
    versions:
    - 10.5.0
    - 10.6.0
    - 10.7.1
  - dependency-name: husky
    versions:
    - 4.3.8
    - 5.0.9
    - 5.1.0
    - 5.1.1
    - 5.1.2
    - 5.1.3
    - 5.2.0
  - dependency-name: mocha
    versions:
    - 8.2.1
    - 8.3.0
    - 8.3.1
  - dependency-name: chai
    versions:
    - 4.2.0
    - 4.3.0
    - 4.3.1
    - 4.3.3
  - dependency-name: spectron
    versions:
    - 13.0.0
